// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfbarayqywttbenevkqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmYmFyYXlxeXd0dGJlbmV2a3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTQ2MTAsImV4cCI6MjA3NDEzMDYxMH0.4aeJXJNb7wTym2T8FaQFmlyXQ95M6Tywpd7H92UrFZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});